name: Vue Front Build and Push


# 1. 이벤트 트리거(on)

on:
    push:
        branches: [main]


# 2. Jobs - runner
jobs:
    build:
        runs-on: ubuntu-latest


# 3. source checkout
        steps:
          - name: source checkout 
            uses: actions/checkout@v2

    

# 4. setup node
          - name: node setup
            uses: actions/setup-node@v2    

# 5. docker build
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1  
    
# 6. docker login
          - name: Docker Login
            uses: docker/login-action@v2
            with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}

# 7. docker build and push
          - name: Push Image
            uses: docker/build-push-action@v2
            with:
                context: ./
                file: ./Dockerfile
                push: true
             # DOCKER BUILD -T WARDKEY/IMAGE/TAGE
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/vueapp:${{ github.sha }}


# 파이프라인 작성이 끝나면 로컬 콘솔에서 이미지 빌드 , 실행
# docker build ~~~~
# docker run port(8080:8080) container_name image